# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    robot_without_rot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    rotation_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_controller:
  ros__parameters:
    joints:
      - Z_Translation
      - X_Translation
      - Y_Translation
      - Rotation
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
robot_without_rot_controller:
  ros__parameters:
    joints:
      - Z_Translation
      - X_Translation
      - Y_Translation
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
rotation_controller:
  ros__parameters:
    joints:
      - Rotation
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity